### ISSUE TITLE
Remove useless branches

### ISSUE THREAD

**Issue by coke** [perl6/doc#1151]
```
$ git branch -r --merged
```

- [x] origin/GT#155
- [x] origin/HEAD -> origin/master
- [x] origin/coke/levenshtein
- [x] origin/consistent-return-types
- [x] origin/highlights
- [x] origin/less-seems
- [x] origin/master
- [x] origin/minor-spelling
- [x] origin/molecules-patch-1
- [x] origin/molecules-patch-2
- [x] origin/return-ways-explanation
- [x] origin/rmdir-tree
- [x] origin/ronaldxs-fix-contributing-link

Seems like everything here (except HEAD) is safe to delete. Not sure if we have a branch policy, but on projects like this, I'm used to delete-once-merged.

**Comment by AlexDaniel** [comment]
Done I think.

**Comment by AlexDaniel** [comment]
Wait, let's take it one step further.

**Comment by AlexDaniel** [comment]
These are old but not merged:
- [ ] makefile
- [ ] autarch/use-new-pod-to-html
- [ ] autarch/use-perl6-org-design
- [ ] usage_statements
- [ ] supplied

**Comment by coke** [comment]
We don't need a master ticket for branches in progress; each of these can either be tied to an existing ticket, or tied to a particular developer's workspace.

And if we need the list, we can always use git to get it.

Finally, the makefile branch was intended to give us a way to parallelize the build using stable tech; that ship has sailed with the addition of the --parallel and --no-proc-async flags, we've switched to using Perl 6 to handle the multi-tasking.  Someone can feel free to delete if they want.
