### ISSUE TITLE
Terminology normalization

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2015]
## The problem

Looking for `handles` for some reason I have found that file handle appear at least in that form or in the `filehandle` form. We should try and normalize terminology across all the documents, and this is only an example. When normalization is done, we should turn it into a test later on. 

## Suggestions

Agree on one single form for terms that are frequently appearing in the documentation. Please add terms below, and let's discuss in the comments which form is preferred.

* [x] file handle, filehandle, file-handle → filehandle
* [x] runtime, run-time → runtime
* [x] short-hand, shorthand →shorthand
* [x] look-ahead, lookahead →lookahead
* [x] look-behind, lookbehind →lookbehind
* [x] smart-match, smartmatch, smart-matching, smart-matches → smartmatch

* [x] Add the words to the xt/word-variants.t test
* [x] Add them to the writing-docs/STYLEGUIDE.md

**Comment by JJ** [comment]
@ufobat I see you have edited this, but could you please indicate the commit where you made that change?

**Comment by AlexDaniel** [comment]
“filehandle” is done now, but we need tests.

**Comment by rafaelschipiura** [comment]
@chsanch You can also add the words you changed to the doc/Type/X/IO/DoesNotExist.pod6 test.

**Comment by JJ** [comment]
El mar., 29 may. 2018 a las 20:12, Rafael Schipiura (<
notifications@github.com>) escribió:

> @chsanch <https://github.com/chsanch> You can also add the words you
> changed to the doc/Type/X/IO/DoesNotExist.pod6 test.
>

You probably mean   xt/word-variants.t

**Comment by chsanch** [comment]
Ok, I'm on it.
