### ISSUE TITLE
Checklist for 2019.07

### ISSUE THREAD

**Issue by JJ** [perl6/doc#2905]
# Additions:

* [ ] Added an X::Cannot::Map exception [fd8a00a3][ef8899f6][a804ed0f]
* [ ] Telemetry's snap now also accepts an optional "checkpoint" message [afc9f849]
* [ ] Telemetry: allow snap :heap for heap snapshots [90e18b65][0c80e067]
* [ ] CompUnit::Repository::FileSystem objects can now also be created from an IO::Path [e9bbefd3][b2e72d6d]
* [ ] Added support for use v6.e.PREVIEW [d4afd480]
* [ ] EVAL now supports a :check flag to just check syntax (like perl6 -c) [d41f162d][5b3a8ce0]
* [ ] Implemented support for Kernel.free-memory and Kernel.total-memory [31671f8f]
* [ ] Added the CachedIterator role for creating iterators on cached lists [94ba19f7][a4d38539]
* [ ] By default a parametric role group would now choose non-signatured candidate for introspection; if there is no such candidate then the first one would be chosen [6c023546]
* [ ] Added --confprog, a way to configure the behavior of some moarvm-internal systems like the profiler [97334711]

# Removals:

* [ ] Removed :where support for Signature/Parameter.perl [4cfe5ec1]
* [ ] Removed several internal functions from CORE:: and SETTING:: namespaces [45eb1c5f][ed074cd1][80185031][bf57f762]
* [ ] Removed wrappers for no longer existing internal function from RESTRICTED setting [47832fe1]
* [ ] Removed Compiler::build-date [019ccf05][35423a6e]
* [ ] Removed the timestamp in Distro's desc [2d4d2ca0]
* [ ] Removed unused %opts argument from Perl6::World::load_module_early [bc764c2e]

**Comment by JJ** [comment]
(this is provisional until I find the script I created that links that to the corresponding commit)

**Comment by stoned** [comment]
Kernel.free-memory and Kernel.total-memory had been document since 755b28b730882baff75d5e6cb8399ffe4488bc58

**Comment by coke** [comment]
CachedIterator is not part of rakudo source, it's only mentioned in the Changelog.

**Comment by coke** [comment]
--confprog doesn't look like a user facing item, but something for core developers only.

**Comment by arkiuat** [comment]
I had time to go back and look more closely into the change made to CompUnit::Repository::FileSystem to confirm the above conjecture, and checked off the second-last ticky box. The fix was done to bring the code into conformity with the doc, so no doc changes are needed since the bug was never documented.
