### ISSUE TITLE
checklist for 2024.01

### ISSUE THREAD

**Issue by coke** [perl6/doc#4455]
+ Improvements:
    * [ ] Make dd show types better [57bda882]
    * [ ] Make use of native unsigned integers better performant [c0340fc7]
    * [ ] Add dispatchers for handling unassigned elements in hashes and arrays
      resulting in better performance in some specific idioms [0e2e20a4]
      [fa4cc823][1ef51856][70d53fb6][79728078]

+ Additions:
    * [ ] New nqp::syscall/register/delegate/track/guard ops as shortcuts
      to otherwise very verbose nqp::dispatch arguments [a3645497][2d8839e1]
    * [ ] Document dispatchers [9b179a55][690c6c01][93f2a8aa][bafa5ad4]
      [f0673003][2aa796fd][ac5c89bb][6ba5ee53][1721f00b][5394496a][5dd90860]
      [e0952486][9a07a6c8][87bcbe6a][b356bbfd][f651e9d6][2e9c0cc1][26ab5c21]
      [4dc737c3][62a67452][93c31ce9][e002a7a8][7456e6dc][b94e98fc][6819b9de]
      [bb384c41][fd5e4da6][f2b09f7e][6f75ed00][808885d7][fc670bb8][8bf824a5]
      [2cfa0768][d6d7d154][45b1025a][6b6548d8][d327d14a][120a06c7][95770d31]
      [f13ba1d0][12db03a5][11734d4f]

+ Fixes:
    * [ ] Handle .extension("foo") on IOs without extension as if :parts(0) is
      specified [8cda0bc6]

+ Deprecations:
    * [ ] Deprecate many Distribution::Resource methods [c83eccfa][cd231798][4d797bbb]
      [7ac9aeab]
    * [ ] Deprecate the use of PERL6LIB [47fdc20d]
